.PHONY: \
	do \
	info \
	plan-do \
	plan-undo \
	setup \
	undo

info:
	@echo "Just wait"

setup:
	@echo "noop"

###################
# main
###################
plan-do: info

plan-undo: info

do:
	sleep 30

undo:
	@echo "noop"
