.PHONY: info
info:
	@echo "Just wait"

.PHONY: setup
setup:
	@echo "noop"

###################
# main
###################
.PHONY: plan-do
plan-do: info

.PHONY: plan-undo
plan-undo: info

.PHONY: do
do:
	sleep 30

.PHONY: undo
undo:
	@echo "noop"
